### ISSUE TITLE
Request for code release

### ISSUE THREAD

**Issue by Tloops** [Kid-Liet/IMSE#1]
@Kid-Liet  Hello! I came across your paper, and I want to say that I found it really interesting. However, I noticed that you didn't include any source code in this repository. I was wondering if there is any plan to make it available in the future? Thank you for your time.

**Comment by Kid-Liet** [comment]
Thank you for your attention. We will release it this week as much as possible, because there are many experimental contents and it is difficult to organize them into readable code.

**Comment by Tloops** [comment]
Thank you for your prompt response. I completely understand that organizing experimental contents into readable code can be a challenging task. I will be waiting for it.

**Comment by Kid-Liet** [comment]
Hello, we have uploaded the full 2D version and the pure 3D version. Next week, we will update the full 3D version. A literature explanation on code details will also be provided later. If you currently encounter any issues, you can add me to WeChat: kid_ liet
